# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mz93pi9BsWAKRGPFr6eU7Ra_H8Z9uSpR
"""

import cv2
import numpy as np
from skimage.util import random_noise
import matplotlib.pyplot as plt


img = cv2.imread('/content/images.jpg')

if img is None:
    raise ValueError("Image could not be loaded.")


img_float = img.astype(np.float32) / 255

gaussian = random_noise(img_float, mode='gaussian', var=0.01)
salt_pepper = random_noise(img_float, mode='s&p', amount=0.05)
speckle = random_noise(img_float, mode='speckle', var=0.04)
poisson = random_noise(img_float, mode='poisson')


rows, cols, channels = img_float.shape
X, Y = np.meshgrid(np.arange(cols), np.arange(rows))

sine = 0.1 * (
    np.sin(2 * np.pi * 10 * X / cols) +
    np.sin(2 * np.pi * 5 * Y / rows)
)

periodic = np.clip(
    img_float + np.stack([sine] * channels, axis=-1),
    0, 1
)


noisy_images = [gaussian, salt_pepper, speckle, poisson, periodic]
titles = ['Gaussian', 'Salt & Pepper', 'Speckle', 'Poisson', 'Periodic']


fig, axes = plt.subplots(1, 6, figsize=(20, 4))

axes[0].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
axes[0].set_title('Original')
axes[0].axis('off')

for i, (image, title) in enumerate(zip(noisy_images, titles)):
    axes[i + 1].imshow(cv2.cvtColor((image * 255).astype(np.uint8),
                                     cv2.COLOR_BGR2RGB))
    axes[i + 1].set_title(title)
    axes[i + 1].axis('off')

plt.tight_layout()
plt.show()