# -*- coding: utf-8 -*-
"""Image_Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14pp5hgXLt8Rl0Q6UWjih7M5g0jnc35Fl

**Lab_Exp-1**

*Practice Basic Image Processing Operations*
"""

import cv2
import matplotlib.pyplot as plt

image = cv2.imread('/content/drive/MyDrive/image.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Basic operations
gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
resized = cv2.resize(image, (150, 150))
cropped = image[100:200, 100:200]
rotated = cv2.rotate(image, cv2.ROTATE_90_CLOCKWISE)
flipped = cv2.flip(image, 1)
bright = cv2.convertScaleAbs(image, alpha=1, beta=50)

# Displaying
images = [image, gray, resized, cropped, rotated, flipped, bright]
titles = ['Original', 'Grayscale', 'Resized', 'Cropped',
          'Rotated', 'Flipped', 'Brightness']

plt.figure(figsize=(12, 8))

for i in range(len(images)):
    plt.subplot(2, 4, i + 1)
    plt.imshow(images[i], cmap='gray' if i == 1 else None)
    plt.title(titles[i])
    plt.axis('off')

plt.tight_layout()
plt.show()

"""*Demonstrate Sampling and Quantization*"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Convert image to RGB
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Sampling: reduce image size by half
h, w, _ = image.shape
sampled = cv2.resize(image, (w // 2, h // 2))
sampled = cv2.resize(sampled, (w, h))

# Quantization: reduce to 4 levels
quantized = (image // 64) * 64

# Display
images = [image, sampled, quantized]
titles = ['Original', 'Sampled', 'Quantized']

plt.figure(figsize=(12, 4))

for i in range(3):
    plt.subplot(1, 3, i + 1)
    plt.imshow(images[i])
    plt.title(titles[i])
    plt.axis('off')

plt.show()

"""*Demonstrate 2D Transforms DFT, DCT*"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from scipy.fftpack import dct, idct

# Convert image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY).astype(np.float32)

# DFT
dft = cv2.dft(gray, flags=cv2.DFT_COMPLEX_OUTPUT)
dft = np.fft.fftshift(dft)

# Magnitude spectrum
magnitude = 20 * np.log(
    cv2.magnitude(dft[:, :, 0], dft[:, :, 1]) + 1
)

# Inverse DFT
dft = np.fft.ifftshift(dft)
reconstructed_dft = cv2.idft(dft)
reconstructed_dft = cv2.magnitude(
    reconstructed_dft[:, :, 0],
    reconstructed_dft[:, :, 1]
)

# DCT
dct_image = dct(dct(gray.T, norm='ortho').T, norm='ortho')

# Inverse DCT
reconstructed_dct = idct(
    idct(dct_image.T, norm='ortho').T,
    norm='ortho'
)

# Displaying
plt.figure(figsize=(12, 8))

plt.subplot(2, 3, 1)
plt.imshow(gray, cmap='gray')
plt.title('Grayscale')
plt.axis('off')

plt.subplot(2, 3, 2)
plt.imshow(magnitude, cmap='gray')
plt.title('DFT')
plt.axis('off')

plt.subplot(2, 3, 3)
plt.imshow(reconstructed_dft, cmap='gray')
plt.title('Inverse DFT')
plt.axis('off')

plt.subplot(2, 3, 4)
plt.imshow(np.log(abs(dct_image) + 1), cmap='gray')
plt.title('DCT')
plt.axis('off')

plt.subplot(2, 3, 5)
plt.imshow(reconstructed_dct, cmap='gray')
plt.title('Inverse DCT')
plt.axis('off')

plt.tight_layout()
plt.show()